### ISSUE TITLE
Reduce risk of instability in VPE IPs

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-vpe-gateway#343]
### Description

Any insertion / deletion in list at https://github.com/terraform-ibm-modules/terraform-ibm-vpe-module/blob/f0ca43341640f18bfbf54431c84eaae0c039c704/variables.tf#L61C28-L61C28)](https://github.com/terraform-ibm-modules/terraform-ibm-vpe-module/blob/f0ca43341640f18bfbf54431c84eaae0c039c704/variables.tf#L61C28-L61C28 results in the VPE IP changing for the services after the modification in the list.

This is problematic for consumers that have an expectation of IP stability. See whether we could come up with a data structure here that does not result in this issue - eg: a map.

**Comment by Aashiq-J** [comment]
Pr merged. Closing issue.
