### ISSUE TITLE
Give more flexibility in the VPE name

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-vpe-gateway#344]
### Description

[](https://github.com/terraform-ibm-modules/terraform-ibm-vpe-module/blob/f0ca43341640f18bfbf54431c84eaae0c039c704/main.tf#L86C76-L86C76)

Provide a way for the caller to specify own name

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
PR under review https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/pull/362
