### ISSUE TITLE
vpe to container registry result in error

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-vpe-gateway#390]
See change at https://cloud.ibm.com/docs/Registry?topic=Registry-registry_notices_vpe&interface=ui

**Comment by toddgiguere** [comment]
The CRN pattern for container-registry does not follow the exact format of region codes. Currently there are no APIs to determine dynamically, so had to hard-code region to domain mapping based on following chart: https://cloud.ibm.com/docs/Registry?topic=Registry-registry_vpe&interface=ui#registry_vpe_endpoint_setup
