### ISSUE TITLE
Give option to name vpe ips

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-vpe-gateway#435]
### Description

Current logic let the cloud stack pick a random name as the name attribute is not passed https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/blob/3707f509e14c4392e742a6e239a5c51a2d3c838f/main.tf#L64

There is a limit of 63 chars on the name. The current logic at https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/blob/3707f509e14c4392e742a6e239a5c51a2d3c838f/main.tf#L35 and https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/blob/3707f509e14c4392e742a6e239a5c51a2d3c838f/main.tf#L43 may generate longer than names, so this needs to be factors in the implementation

**Comment by shemau** [comment]
🎉 This PR is included in version 4.1.0 🎉
