### ISSUE TITLE
[terraform-ibm-vpe-gateway] Update required ibm provider version to `>=1.61.0, <2.0.0` to pull in fix for known issue

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-vpe-gateway#472]
A fix for https://github.com/IBM-Cloud/terraform-provider-ibm/pull/4988 was included in the 1.61.0 release, so we should update the required ibm provider version to `>=1.61.0, <2.0.0` so we ensure this fix is included.

**Comment by shemau** [comment]
The provider version is 1.61.0, so I am closing this issue.
