### ISSUE TITLE
Add eu-fr2 to domain mappings

### ISSUE THREAD

**Issue by pauljegouic** [terraform-ibm-modules/terraform-ibm-vpe-gateway#545]
The module does not handle the eu-fr2 region, please add it to the list : 

https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/blob/main/service_endpoints.tf#L46

**Comment by Aashiq-J** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-vpe-gateway/pull/546

**Comment by Aashiq-J** [comment]
PR merged. Closing issue
